# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/server/CMakeFiles /root/server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test_pthread

# Build rule for target.
test_pthread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_pthread
.PHONY : test_pthread

# fast build rule for target.
test_pthread/fast:
	$(MAKE) -f CMakeFiles/test_pthread.dir/build.make CMakeFiles/test_pthread.dir/build
.PHONY : test_pthread/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named my_test_http_server

# Build rule for target.
my_test_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 my_test_http_server
.PHONY : my_test_http_server

# fast build rule for target.
my_test_http_server/fast:
	$(MAKE) -f CMakeFiles/my_test_http_server.dir/build.make CMakeFiles/my_test_http_server.dir/build
.PHONY : my_test_http_server/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_tcp_server

# Build rule for target.
test_tcp_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_tcp_server
.PHONY : test_tcp_server

# fast build rule for target.
test_tcp_server/fast:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/build
.PHONY : test_tcp_server/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named dwframe

# Build rule for target.
dwframe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dwframe
.PHONY : dwframe

# fast build rule for target.
dwframe/fast:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/build
.PHONY : dwframe/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

dwframe/IoManager.o: dwframe/IoManager.cc.o

.PHONY : dwframe/IoManager.o

# target to build an object file
dwframe/IoManager.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/IoManager.cc.o
.PHONY : dwframe/IoManager.cc.o

dwframe/IoManager.i: dwframe/IoManager.cc.i

.PHONY : dwframe/IoManager.i

# target to preprocess a source file
dwframe/IoManager.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/IoManager.cc.i
.PHONY : dwframe/IoManager.cc.i

dwframe/IoManager.s: dwframe/IoManager.cc.s

.PHONY : dwframe/IoManager.s

# target to generate assembly for a file
dwframe/IoManager.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/IoManager.cc.s
.PHONY : dwframe/IoManager.cc.s

dwframe/Tcp_server.o: dwframe/Tcp_server.cc.o

.PHONY : dwframe/Tcp_server.o

# target to build an object file
dwframe/Tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/Tcp_server.cc.o
.PHONY : dwframe/Tcp_server.cc.o

dwframe/Tcp_server.i: dwframe/Tcp_server.cc.i

.PHONY : dwframe/Tcp_server.i

# target to preprocess a source file
dwframe/Tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/Tcp_server.cc.i
.PHONY : dwframe/Tcp_server.cc.i

dwframe/Tcp_server.s: dwframe/Tcp_server.cc.s

.PHONY : dwframe/Tcp_server.s

# target to generate assembly for a file
dwframe/Tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/Tcp_server.cc.s
.PHONY : dwframe/Tcp_server.cc.s

dwframe/address.o: dwframe/address.cc.o

.PHONY : dwframe/address.o

# target to build an object file
dwframe/address.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/address.cc.o
.PHONY : dwframe/address.cc.o

dwframe/address.i: dwframe/address.cc.i

.PHONY : dwframe/address.i

# target to preprocess a source file
dwframe/address.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/address.cc.i
.PHONY : dwframe/address.cc.i

dwframe/address.s: dwframe/address.cc.s

.PHONY : dwframe/address.s

# target to generate assembly for a file
dwframe/address.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/address.cc.s
.PHONY : dwframe/address.cc.s

dwframe/bytearray.o: dwframe/bytearray.cc.o

.PHONY : dwframe/bytearray.o

# target to build an object file
dwframe/bytearray.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/bytearray.cc.o
.PHONY : dwframe/bytearray.cc.o

dwframe/bytearray.i: dwframe/bytearray.cc.i

.PHONY : dwframe/bytearray.i

# target to preprocess a source file
dwframe/bytearray.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/bytearray.cc.i
.PHONY : dwframe/bytearray.cc.i

dwframe/bytearray.s: dwframe/bytearray.cc.s

.PHONY : dwframe/bytearray.s

# target to generate assembly for a file
dwframe/bytearray.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/bytearray.cc.s
.PHONY : dwframe/bytearray.cc.s

dwframe/config.o: dwframe/config.cc.o

.PHONY : dwframe/config.o

# target to build an object file
dwframe/config.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/config.cc.o
.PHONY : dwframe/config.cc.o

dwframe/config.i: dwframe/config.cc.i

.PHONY : dwframe/config.i

# target to preprocess a source file
dwframe/config.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/config.cc.i
.PHONY : dwframe/config.cc.i

dwframe/config.s: dwframe/config.cc.s

.PHONY : dwframe/config.s

# target to generate assembly for a file
dwframe/config.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/config.cc.s
.PHONY : dwframe/config.cc.s

dwframe/fd_manager.o: dwframe/fd_manager.cc.o

.PHONY : dwframe/fd_manager.o

# target to build an object file
dwframe/fd_manager.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/fd_manager.cc.o
.PHONY : dwframe/fd_manager.cc.o

dwframe/fd_manager.i: dwframe/fd_manager.cc.i

.PHONY : dwframe/fd_manager.i

# target to preprocess a source file
dwframe/fd_manager.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/fd_manager.cc.i
.PHONY : dwframe/fd_manager.cc.i

dwframe/fd_manager.s: dwframe/fd_manager.cc.s

.PHONY : dwframe/fd_manager.s

# target to generate assembly for a file
dwframe/fd_manager.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/fd_manager.cc.s
.PHONY : dwframe/fd_manager.cc.s

dwframe/fiber.o: dwframe/fiber.cc.o

.PHONY : dwframe/fiber.o

# target to build an object file
dwframe/fiber.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/fiber.cc.o
.PHONY : dwframe/fiber.cc.o

dwframe/fiber.i: dwframe/fiber.cc.i

.PHONY : dwframe/fiber.i

# target to preprocess a source file
dwframe/fiber.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/fiber.cc.i
.PHONY : dwframe/fiber.cc.i

dwframe/fiber.s: dwframe/fiber.cc.s

.PHONY : dwframe/fiber.s

# target to generate assembly for a file
dwframe/fiber.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/fiber.cc.s
.PHONY : dwframe/fiber.cc.s

dwframe/hook.o: dwframe/hook.cc.o

.PHONY : dwframe/hook.o

# target to build an object file
dwframe/hook.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/hook.cc.o
.PHONY : dwframe/hook.cc.o

dwframe/hook.i: dwframe/hook.cc.i

.PHONY : dwframe/hook.i

# target to preprocess a source file
dwframe/hook.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/hook.cc.i
.PHONY : dwframe/hook.cc.i

dwframe/hook.s: dwframe/hook.cc.s

.PHONY : dwframe/hook.s

# target to generate assembly for a file
dwframe/hook.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/hook.cc.s
.PHONY : dwframe/hook.cc.s

dwframe/http/http.o: dwframe/http/http.cc.o

.PHONY : dwframe/http/http.o

# target to build an object file
dwframe/http/http.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http.cc.o
.PHONY : dwframe/http/http.cc.o

dwframe/http/http.i: dwframe/http/http.cc.i

.PHONY : dwframe/http/http.i

# target to preprocess a source file
dwframe/http/http.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http.cc.i
.PHONY : dwframe/http/http.cc.i

dwframe/http/http.s: dwframe/http/http.cc.s

.PHONY : dwframe/http/http.s

# target to generate assembly for a file
dwframe/http/http.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http.cc.s
.PHONY : dwframe/http/http.cc.s

dwframe/http/http11_parser.rl.o: dwframe/http/http11_parser.rl.cc.o

.PHONY : dwframe/http/http11_parser.rl.o

# target to build an object file
dwframe/http/http11_parser.rl.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http11_parser.rl.cc.o
.PHONY : dwframe/http/http11_parser.rl.cc.o

dwframe/http/http11_parser.rl.i: dwframe/http/http11_parser.rl.cc.i

.PHONY : dwframe/http/http11_parser.rl.i

# target to preprocess a source file
dwframe/http/http11_parser.rl.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http11_parser.rl.cc.i
.PHONY : dwframe/http/http11_parser.rl.cc.i

dwframe/http/http11_parser.rl.s: dwframe/http/http11_parser.rl.cc.s

.PHONY : dwframe/http/http11_parser.rl.s

# target to generate assembly for a file
dwframe/http/http11_parser.rl.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http11_parser.rl.cc.s
.PHONY : dwframe/http/http11_parser.rl.cc.s

dwframe/http/http_parser.o: dwframe/http/http_parser.cc.o

.PHONY : dwframe/http/http_parser.o

# target to build an object file
dwframe/http/http_parser.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_parser.cc.o
.PHONY : dwframe/http/http_parser.cc.o

dwframe/http/http_parser.i: dwframe/http/http_parser.cc.i

.PHONY : dwframe/http/http_parser.i

# target to preprocess a source file
dwframe/http/http_parser.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_parser.cc.i
.PHONY : dwframe/http/http_parser.cc.i

dwframe/http/http_parser.s: dwframe/http/http_parser.cc.s

.PHONY : dwframe/http/http_parser.s

# target to generate assembly for a file
dwframe/http/http_parser.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_parser.cc.s
.PHONY : dwframe/http/http_parser.cc.s

dwframe/http/http_server.o: dwframe/http/http_server.cc.o

.PHONY : dwframe/http/http_server.o

# target to build an object file
dwframe/http/http_server.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_server.cc.o
.PHONY : dwframe/http/http_server.cc.o

dwframe/http/http_server.i: dwframe/http/http_server.cc.i

.PHONY : dwframe/http/http_server.i

# target to preprocess a source file
dwframe/http/http_server.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_server.cc.i
.PHONY : dwframe/http/http_server.cc.i

dwframe/http/http_server.s: dwframe/http/http_server.cc.s

.PHONY : dwframe/http/http_server.s

# target to generate assembly for a file
dwframe/http/http_server.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_server.cc.s
.PHONY : dwframe/http/http_server.cc.s

dwframe/http/http_session.o: dwframe/http/http_session.cc.o

.PHONY : dwframe/http/http_session.o

# target to build an object file
dwframe/http/http_session.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_session.cc.o
.PHONY : dwframe/http/http_session.cc.o

dwframe/http/http_session.i: dwframe/http/http_session.cc.i

.PHONY : dwframe/http/http_session.i

# target to preprocess a source file
dwframe/http/http_session.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_session.cc.i
.PHONY : dwframe/http/http_session.cc.i

dwframe/http/http_session.s: dwframe/http/http_session.cc.s

.PHONY : dwframe/http/http_session.s

# target to generate assembly for a file
dwframe/http/http_session.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/http_session.cc.s
.PHONY : dwframe/http/http_session.cc.s

dwframe/http/httpclient_parser.rl.o: dwframe/http/httpclient_parser.rl.cc.o

.PHONY : dwframe/http/httpclient_parser.rl.o

# target to build an object file
dwframe/http/httpclient_parser.rl.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/httpclient_parser.rl.cc.o
.PHONY : dwframe/http/httpclient_parser.rl.cc.o

dwframe/http/httpclient_parser.rl.i: dwframe/http/httpclient_parser.rl.cc.i

.PHONY : dwframe/http/httpclient_parser.rl.i

# target to preprocess a source file
dwframe/http/httpclient_parser.rl.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/httpclient_parser.rl.cc.i
.PHONY : dwframe/http/httpclient_parser.rl.cc.i

dwframe/http/httpclient_parser.rl.s: dwframe/http/httpclient_parser.rl.cc.s

.PHONY : dwframe/http/httpclient_parser.rl.s

# target to generate assembly for a file
dwframe/http/httpclient_parser.rl.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/httpclient_parser.rl.cc.s
.PHONY : dwframe/http/httpclient_parser.rl.cc.s

dwframe/http/servlet.o: dwframe/http/servlet.cc.o

.PHONY : dwframe/http/servlet.o

# target to build an object file
dwframe/http/servlet.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/servlet.cc.o
.PHONY : dwframe/http/servlet.cc.o

dwframe/http/servlet.i: dwframe/http/servlet.cc.i

.PHONY : dwframe/http/servlet.i

# target to preprocess a source file
dwframe/http/servlet.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/servlet.cc.i
.PHONY : dwframe/http/servlet.cc.i

dwframe/http/servlet.s: dwframe/http/servlet.cc.s

.PHONY : dwframe/http/servlet.s

# target to generate assembly for a file
dwframe/http/servlet.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/http/servlet.cc.s
.PHONY : dwframe/http/servlet.cc.s

dwframe/log.o: dwframe/log.cc.o

.PHONY : dwframe/log.o

# target to build an object file
dwframe/log.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/log.cc.o
.PHONY : dwframe/log.cc.o

dwframe/log.i: dwframe/log.cc.i

.PHONY : dwframe/log.i

# target to preprocess a source file
dwframe/log.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/log.cc.i
.PHONY : dwframe/log.cc.i

dwframe/log.s: dwframe/log.cc.s

.PHONY : dwframe/log.s

# target to generate assembly for a file
dwframe/log.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/log.cc.s
.PHONY : dwframe/log.cc.s

dwframe/scheduler.o: dwframe/scheduler.cc.o

.PHONY : dwframe/scheduler.o

# target to build an object file
dwframe/scheduler.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/scheduler.cc.o
.PHONY : dwframe/scheduler.cc.o

dwframe/scheduler.i: dwframe/scheduler.cc.i

.PHONY : dwframe/scheduler.i

# target to preprocess a source file
dwframe/scheduler.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/scheduler.cc.i
.PHONY : dwframe/scheduler.cc.i

dwframe/scheduler.s: dwframe/scheduler.cc.s

.PHONY : dwframe/scheduler.s

# target to generate assembly for a file
dwframe/scheduler.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/scheduler.cc.s
.PHONY : dwframe/scheduler.cc.s

dwframe/socket.o: dwframe/socket.cc.o

.PHONY : dwframe/socket.o

# target to build an object file
dwframe/socket.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/socket.cc.o
.PHONY : dwframe/socket.cc.o

dwframe/socket.i: dwframe/socket.cc.i

.PHONY : dwframe/socket.i

# target to preprocess a source file
dwframe/socket.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/socket.cc.i
.PHONY : dwframe/socket.cc.i

dwframe/socket.s: dwframe/socket.cc.s

.PHONY : dwframe/socket.s

# target to generate assembly for a file
dwframe/socket.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/socket.cc.s
.PHONY : dwframe/socket.cc.s

dwframe/socket_stream.o: dwframe/socket_stream.cc.o

.PHONY : dwframe/socket_stream.o

# target to build an object file
dwframe/socket_stream.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/socket_stream.cc.o
.PHONY : dwframe/socket_stream.cc.o

dwframe/socket_stream.i: dwframe/socket_stream.cc.i

.PHONY : dwframe/socket_stream.i

# target to preprocess a source file
dwframe/socket_stream.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/socket_stream.cc.i
.PHONY : dwframe/socket_stream.cc.i

dwframe/socket_stream.s: dwframe/socket_stream.cc.s

.PHONY : dwframe/socket_stream.s

# target to generate assembly for a file
dwframe/socket_stream.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/socket_stream.cc.s
.PHONY : dwframe/socket_stream.cc.s

dwframe/stream.o: dwframe/stream.cc.o

.PHONY : dwframe/stream.o

# target to build an object file
dwframe/stream.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/stream.cc.o
.PHONY : dwframe/stream.cc.o

dwframe/stream.i: dwframe/stream.cc.i

.PHONY : dwframe/stream.i

# target to preprocess a source file
dwframe/stream.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/stream.cc.i
.PHONY : dwframe/stream.cc.i

dwframe/stream.s: dwframe/stream.cc.s

.PHONY : dwframe/stream.s

# target to generate assembly for a file
dwframe/stream.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/stream.cc.s
.PHONY : dwframe/stream.cc.s

dwframe/thread.o: dwframe/thread.cc.o

.PHONY : dwframe/thread.o

# target to build an object file
dwframe/thread.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/thread.cc.o
.PHONY : dwframe/thread.cc.o

dwframe/thread.i: dwframe/thread.cc.i

.PHONY : dwframe/thread.i

# target to preprocess a source file
dwframe/thread.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/thread.cc.i
.PHONY : dwframe/thread.cc.i

dwframe/thread.s: dwframe/thread.cc.s

.PHONY : dwframe/thread.s

# target to generate assembly for a file
dwframe/thread.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/thread.cc.s
.PHONY : dwframe/thread.cc.s

dwframe/timer.o: dwframe/timer.cc.o

.PHONY : dwframe/timer.o

# target to build an object file
dwframe/timer.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/timer.cc.o
.PHONY : dwframe/timer.cc.o

dwframe/timer.i: dwframe/timer.cc.i

.PHONY : dwframe/timer.i

# target to preprocess a source file
dwframe/timer.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/timer.cc.i
.PHONY : dwframe/timer.cc.i

dwframe/timer.s: dwframe/timer.cc.s

.PHONY : dwframe/timer.s

# target to generate assembly for a file
dwframe/timer.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/timer.cc.s
.PHONY : dwframe/timer.cc.s

dwframe/util.o: dwframe/util.cc.o

.PHONY : dwframe/util.o

# target to build an object file
dwframe/util.cc.o:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/util.cc.o
.PHONY : dwframe/util.cc.o

dwframe/util.i: dwframe/util.cc.i

.PHONY : dwframe/util.i

# target to preprocess a source file
dwframe/util.cc.i:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/util.cc.i
.PHONY : dwframe/util.cc.i

dwframe/util.s: dwframe/util.cc.s

.PHONY : dwframe/util.s

# target to generate assembly for a file
dwframe/util.cc.s:
	$(MAKE) -f CMakeFiles/dwframe.dir/build.make CMakeFiles/dwframe.dir/dwframe/util.cc.s
.PHONY : dwframe/util.cc.s

examples/echo_server.o: examples/echo_server.cc.o

.PHONY : examples/echo_server.o

# target to build an object file
examples/echo_server.cc.o:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.o
.PHONY : examples/echo_server.cc.o

examples/echo_server.i: examples/echo_server.cc.i

.PHONY : examples/echo_server.i

# target to preprocess a source file
examples/echo_server.cc.i:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.i
.PHONY : examples/echo_server.cc.i

examples/echo_server.s: examples/echo_server.cc.s

.PHONY : examples/echo_server.s

# target to generate assembly for a file
examples/echo_server.cc.s:
	$(MAKE) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cc.s
.PHONY : examples/echo_server.cc.s

tests/my_test_http_server.o: tests/my_test_http_server.cc.o

.PHONY : tests/my_test_http_server.o

# target to build an object file
tests/my_test_http_server.cc.o:
	$(MAKE) -f CMakeFiles/my_test_http_server.dir/build.make CMakeFiles/my_test_http_server.dir/tests/my_test_http_server.cc.o
.PHONY : tests/my_test_http_server.cc.o

tests/my_test_http_server.i: tests/my_test_http_server.cc.i

.PHONY : tests/my_test_http_server.i

# target to preprocess a source file
tests/my_test_http_server.cc.i:
	$(MAKE) -f CMakeFiles/my_test_http_server.dir/build.make CMakeFiles/my_test_http_server.dir/tests/my_test_http_server.cc.i
.PHONY : tests/my_test_http_server.cc.i

tests/my_test_http_server.s: tests/my_test_http_server.cc.s

.PHONY : tests/my_test_http_server.s

# target to generate assembly for a file
tests/my_test_http_server.cc.s:
	$(MAKE) -f CMakeFiles/my_test_http_server.dir/build.make CMakeFiles/my_test_http_server.dir/tests/my_test_http_server.cc.s
.PHONY : tests/my_test_http_server.cc.s

tests/test.o: tests/test.cc.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cc.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.o
.PHONY : tests/test.cc.o

tests/test.i: tests/test.cc.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cc.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.i
.PHONY : tests/test.cc.i

tests/test.s: tests/test.cc.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cc.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cc.s
.PHONY : tests/test.cc.s

tests/test_address.o: tests/test_address.cc.o

.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cc.o:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.o
.PHONY : tests/test_address.cc.o

tests/test_address.i: tests/test_address.cc.i

.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cc.i:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.i
.PHONY : tests/test_address.cc.i

tests/test_address.s: tests/test_address.cc.s

.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cc.s:
	$(MAKE) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cc.s
.PHONY : tests/test_address.cc.s

tests/test_bytearray.o: tests/test_bytearray.cc.o

.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cc.o:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.o
.PHONY : tests/test_bytearray.cc.o

tests/test_bytearray.i: tests/test_bytearray.cc.i

.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cc.i:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.i
.PHONY : tests/test_bytearray.cc.i

tests/test_bytearray.s: tests/test_bytearray.cc.s

.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cc.s:
	$(MAKE) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cc.s
.PHONY : tests/test_bytearray.cc.s

tests/test_config.o: tests/test_config.cc.o

.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cc.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.o
.PHONY : tests/test_config.cc.o

tests/test_config.i: tests/test_config.cc.i

.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cc.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.i
.PHONY : tests/test_config.cc.i

tests/test_config.s: tests/test_config.cc.s

.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cc.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cc.s
.PHONY : tests/test_config.cc.s

tests/test_fiber.o: tests/test_fiber.cc.o

.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cc.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.o
.PHONY : tests/test_fiber.cc.o

tests/test_fiber.i: tests/test_fiber.cc.i

.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cc.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.i
.PHONY : tests/test_fiber.cc.i

tests/test_fiber.s: tests/test_fiber.cc.s

.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cc.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cc.s
.PHONY : tests/test_fiber.cc.s

tests/test_hook.o: tests/test_hook.cc.o

.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cc.o:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.o
.PHONY : tests/test_hook.cc.o

tests/test_hook.i: tests/test_hook.cc.i

.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cc.i:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.i
.PHONY : tests/test_hook.cc.i

tests/test_hook.s: tests/test_hook.cc.s

.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cc.s:
	$(MAKE) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cc.s
.PHONY : tests/test_hook.cc.s

tests/test_http_parser.o: tests/test_http_parser.cc.o

.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cc.o:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.o
.PHONY : tests/test_http_parser.cc.o

tests/test_http_parser.i: tests/test_http_parser.cc.i

.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cc.i:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.i
.PHONY : tests/test_http_parser.cc.i

tests/test_http_parser.s: tests/test_http_parser.cc.s

.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cc.s:
	$(MAKE) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cc.s
.PHONY : tests/test_http_parser.cc.s

tests/test_http_server.o: tests/test_http_server.cc.o

.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cc.o:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.o
.PHONY : tests/test_http_server.cc.o

tests/test_http_server.i: tests/test_http_server.cc.i

.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cc.i:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.i
.PHONY : tests/test_http_server.cc.i

tests/test_http_server.s: tests/test_http_server.cc.s

.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cc.s:
	$(MAKE) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cc.s
.PHONY : tests/test_http_server.cc.s

tests/test_iomanager.o: tests/test_iomanager.cc.o

.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cc.o:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.o
.PHONY : tests/test_iomanager.cc.o

tests/test_iomanager.i: tests/test_iomanager.cc.i

.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cc.i:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.i
.PHONY : tests/test_iomanager.cc.i

tests/test_iomanager.s: tests/test_iomanager.cc.s

.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cc.s:
	$(MAKE) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cc.s
.PHONY : tests/test_iomanager.cc.s

tests/test_pthread.o: tests/test_pthread.cc.o

.PHONY : tests/test_pthread.o

# target to build an object file
tests/test_pthread.cc.o:
	$(MAKE) -f CMakeFiles/test_pthread.dir/build.make CMakeFiles/test_pthread.dir/tests/test_pthread.cc.o
.PHONY : tests/test_pthread.cc.o

tests/test_pthread.i: tests/test_pthread.cc.i

.PHONY : tests/test_pthread.i

# target to preprocess a source file
tests/test_pthread.cc.i:
	$(MAKE) -f CMakeFiles/test_pthread.dir/build.make CMakeFiles/test_pthread.dir/tests/test_pthread.cc.i
.PHONY : tests/test_pthread.cc.i

tests/test_pthread.s: tests/test_pthread.cc.s

.PHONY : tests/test_pthread.s

# target to generate assembly for a file
tests/test_pthread.cc.s:
	$(MAKE) -f CMakeFiles/test_pthread.dir/build.make CMakeFiles/test_pthread.dir/tests/test_pthread.cc.s
.PHONY : tests/test_pthread.cc.s

tests/test_scheduler.o: tests/test_scheduler.cc.o

.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cc.o:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.o
.PHONY : tests/test_scheduler.cc.o

tests/test_scheduler.i: tests/test_scheduler.cc.i

.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cc.i:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.i
.PHONY : tests/test_scheduler.cc.i

tests/test_scheduler.s: tests/test_scheduler.cc.s

.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cc.s:
	$(MAKE) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cc.s
.PHONY : tests/test_scheduler.cc.s

tests/test_socket.o: tests/test_socket.cc.o

.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cc.o:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.o
.PHONY : tests/test_socket.cc.o

tests/test_socket.i: tests/test_socket.cc.i

.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cc.i:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.i
.PHONY : tests/test_socket.cc.i

tests/test_socket.s: tests/test_socket.cc.s

.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cc.s:
	$(MAKE) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cc.s
.PHONY : tests/test_socket.cc.s

tests/test_tcp_server.o: tests/test_tcp_server.cc.o

.PHONY : tests/test_tcp_server.o

# target to build an object file
tests/test_tcp_server.cc.o:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.o
.PHONY : tests/test_tcp_server.cc.o

tests/test_tcp_server.i: tests/test_tcp_server.cc.i

.PHONY : tests/test_tcp_server.i

# target to preprocess a source file
tests/test_tcp_server.cc.i:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.i
.PHONY : tests/test_tcp_server.cc.i

tests/test_tcp_server.s: tests/test_tcp_server.cc.s

.PHONY : tests/test_tcp_server.s

# target to generate assembly for a file
tests/test_tcp_server.cc.s:
	$(MAKE) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cc.s
.PHONY : tests/test_tcp_server.cc.s

tests/test_util.o: tests/test_util.cc.o

.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cc.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.o
.PHONY : tests/test_util.cc.o

tests/test_util.i: tests/test_util.cc.i

.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cc.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.i
.PHONY : tests/test_util.cc.i

tests/test_util.s: tests/test_util.cc.s

.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cc.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cc.s
.PHONY : tests/test_util.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... echo_server"
	@echo "... test"
	@echo "... test_config"
	@echo "... test_bytearray"
	@echo "... test_pthread"
	@echo "... test_util"
	@echo "... test_fiber"
	@echo "... test_http_server"
	@echo "... test_address"
	@echo "... test_scheduler"
	@echo "... my_test_http_server"
	@echo "... test_iomanager"
	@echo "... test_tcp_server"
	@echo "... test_http_parser"
	@echo "... dwframe"
	@echo "... test_hook"
	@echo "... test_socket"
	@echo "... dwframe/IoManager.o"
	@echo "... dwframe/IoManager.i"
	@echo "... dwframe/IoManager.s"
	@echo "... dwframe/Tcp_server.o"
	@echo "... dwframe/Tcp_server.i"
	@echo "... dwframe/Tcp_server.s"
	@echo "... dwframe/address.o"
	@echo "... dwframe/address.i"
	@echo "... dwframe/address.s"
	@echo "... dwframe/bytearray.o"
	@echo "... dwframe/bytearray.i"
	@echo "... dwframe/bytearray.s"
	@echo "... dwframe/config.o"
	@echo "... dwframe/config.i"
	@echo "... dwframe/config.s"
	@echo "... dwframe/fd_manager.o"
	@echo "... dwframe/fd_manager.i"
	@echo "... dwframe/fd_manager.s"
	@echo "... dwframe/fiber.o"
	@echo "... dwframe/fiber.i"
	@echo "... dwframe/fiber.s"
	@echo "... dwframe/hook.o"
	@echo "... dwframe/hook.i"
	@echo "... dwframe/hook.s"
	@echo "... dwframe/http/http.o"
	@echo "... dwframe/http/http.i"
	@echo "... dwframe/http/http.s"
	@echo "... dwframe/http/http11_parser.rl.o"
	@echo "... dwframe/http/http11_parser.rl.i"
	@echo "... dwframe/http/http11_parser.rl.s"
	@echo "... dwframe/http/http_parser.o"
	@echo "... dwframe/http/http_parser.i"
	@echo "... dwframe/http/http_parser.s"
	@echo "... dwframe/http/http_server.o"
	@echo "... dwframe/http/http_server.i"
	@echo "... dwframe/http/http_server.s"
	@echo "... dwframe/http/http_session.o"
	@echo "... dwframe/http/http_session.i"
	@echo "... dwframe/http/http_session.s"
	@echo "... dwframe/http/httpclient_parser.rl.o"
	@echo "... dwframe/http/httpclient_parser.rl.i"
	@echo "... dwframe/http/httpclient_parser.rl.s"
	@echo "... dwframe/http/servlet.o"
	@echo "... dwframe/http/servlet.i"
	@echo "... dwframe/http/servlet.s"
	@echo "... dwframe/log.o"
	@echo "... dwframe/log.i"
	@echo "... dwframe/log.s"
	@echo "... dwframe/scheduler.o"
	@echo "... dwframe/scheduler.i"
	@echo "... dwframe/scheduler.s"
	@echo "... dwframe/socket.o"
	@echo "... dwframe/socket.i"
	@echo "... dwframe/socket.s"
	@echo "... dwframe/socket_stream.o"
	@echo "... dwframe/socket_stream.i"
	@echo "... dwframe/socket_stream.s"
	@echo "... dwframe/stream.o"
	@echo "... dwframe/stream.i"
	@echo "... dwframe/stream.s"
	@echo "... dwframe/thread.o"
	@echo "... dwframe/thread.i"
	@echo "... dwframe/thread.s"
	@echo "... dwframe/timer.o"
	@echo "... dwframe/timer.i"
	@echo "... dwframe/timer.s"
	@echo "... dwframe/util.o"
	@echo "... dwframe/util.i"
	@echo "... dwframe/util.s"
	@echo "... examples/echo_server.o"
	@echo "... examples/echo_server.i"
	@echo "... examples/echo_server.s"
	@echo "... tests/my_test_http_server.o"
	@echo "... tests/my_test_http_server.i"
	@echo "... tests/my_test_http_server.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_pthread.o"
	@echo "... tests/test_pthread.i"
	@echo "... tests/test_pthread.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcp_server.o"
	@echo "... tests/test_tcp_server.i"
	@echo "... tests/test_tcp_server.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

